version: '3'
services:
  api:
    build:
      context: .
    ports:
      - "8082:8082"
    networks:
      - test-network

  k6:
    image: loadimpact/k6
    volumes:
      - ./test-performance:/scripts
    working_dir: /scripts
    command: run /scripts/scriptTest.js
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
